/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Salva
 */
public class VC_Altas_Hospitales extends javax.swing.JFrame {
    int id,tel;
    String nombre,calle,col,numExt,numInt,ciudad,horario,pagina;
    
    /**
     * Creates new form VC_Altas_Pacientes
     */
    public VC_Altas_Hospitales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_NSS = new javax.swing.JTextField();
        jTF_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTF_Calle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtf_tel = new javax.swing.JTextField();
        jtf_horario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jBtn_Registrar = new javax.swing.JButton();
        jBtn_Salir = new javax.swing.JButton();
        jTF_Colonia = new javax.swing.JTextField();
        jTF_NumExt = new javax.swing.JTextField();
        jTF_NumInt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTF_Ciudad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtf_paginaweb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(188, 189, 190));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 76, 45), 4));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 76, 45));
        jLabel1.setText("HOSPITALES");

        jLabel2.setForeground(new java.awt.Color(29, 76, 45));
        jLabel2.setText("ID:");

        jTF_NSS.setBackground(new java.awt.Color(255, 255, 255));
        jTF_NSS.setForeground(new java.awt.Color(29, 76, 45));

        jTF_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        jTF_Nombre.setForeground(new java.awt.Color(29, 76, 45));

        jLabel3.setForeground(new java.awt.Color(29, 76, 45));
        jLabel3.setText("Nombre:");

        jLabel4.setForeground(new java.awt.Color(29, 76, 45));
        jLabel4.setText("Dirección:");

        jTF_Calle.setBackground(new java.awt.Color(255, 255, 255));
        jTF_Calle.setForeground(new java.awt.Color(29, 76, 45));

        jLabel5.setForeground(new java.awt.Color(29, 76, 45));
        jLabel5.setText("Ciudad:");

        jLabel9.setForeground(new java.awt.Color(29, 76, 45));
        jLabel9.setText("Telefono:");

        jtf_tel.setBackground(new java.awt.Color(255, 255, 255));
        jtf_tel.setForeground(new java.awt.Color(29, 76, 45));

        jtf_horario.setBackground(new java.awt.Color(255, 255, 255));
        jtf_horario.setForeground(new java.awt.Color(29, 76, 45));

        jLabel10.setForeground(new java.awt.Color(29, 76, 45));
        jLabel10.setText("Horario:");

        jBtn_Registrar.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_Registrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBtn_Registrar.setForeground(new java.awt.Color(29, 76, 45));
        jBtn_Registrar.setText("Registrar");
        jBtn_Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RegistrarActionPerformed(evt);
            }
        });

        jBtn_Salir.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_Salir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBtn_Salir.setForeground(new java.awt.Color(29, 76, 45));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        jTF_Colonia.setBackground(new java.awt.Color(255, 255, 255));
        jTF_Colonia.setForeground(new java.awt.Color(29, 76, 45));

        jTF_NumExt.setBackground(new java.awt.Color(255, 255, 255));
        jTF_NumExt.setForeground(new java.awt.Color(29, 76, 45));

        jTF_NumInt.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setForeground(new java.awt.Color(29, 76, 45));
        jLabel11.setText("Calle");

        jLabel12.setForeground(new java.awt.Color(29, 76, 45));
        jLabel12.setText("Colonia");

        jLabel13.setForeground(new java.awt.Color(29, 76, 45));
        jLabel13.setText("Int");

        jLabel14.setForeground(new java.awt.Color(29, 76, 45));
        jLabel14.setText("Ext");

        jTF_Ciudad.setBackground(new java.awt.Color(255, 255, 255));
        jTF_Ciudad.setForeground(new java.awt.Color(29, 76, 45));

        jLabel15.setForeground(new java.awt.Color(29, 76, 45));
        jLabel15.setText("Página Web:");

        jtf_paginaweb.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_NSS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTF_Nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTF_Ciudad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_tel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_horario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_paginaweb, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTF_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel11)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel12)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_NumExt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_NumInt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel13)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel14)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jBtn_Registrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jBtn_Salir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_NSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTF_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_NumExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_NumInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTF_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtf_paginaweb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Registrar)
                    .addComponent(jBtn_Salir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "¿Ha terminado de realizar sus registros?",
                "Confirmación", JOptionPane.YES_NO_OPTION);

        if (x == 0) {
            VC_Main f_Main = new VC_Main();

            f_Main.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_jBtn_SalirActionPerformed

    private void jBtn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RegistrarActionPerformed
        id = Integer.parseInt(this.jTF_NSS.getText());
        nombre = "'"+this.jTF_Nombre.getText()+"'";
        calle = "'"+this.jTF_Calle.getText()+"'";
        col = "'"+this.jTF_Colonia.getText()+"'";
        numExt = "'"+this.jTF_NumExt.getText()+"'";
        numInt = "'"+this.jTF_NumInt.getText()+"'";
        ciudad = "'"+this.jTF_Ciudad.getText()+"'";
        tel = Integer.parseInt(this.jtf_tel.getText());
        horario = "'"+this.jtf_horario.getText()+"'";
        pagina = "'"+this.jtf_paginaweb.getText()+"'";
        
        String query = "INSERT INTO hospital VALUES("+id+","+nombre+","+calle+","+col+","+numExt+","+numInt+","+ciudad+","+tel+","+horario+","+pagina+")"+";";
        
        try {
            Connection con = ConexionBD.getConexion(ConexionBD.con);
            PreparedStatement st = con.prepareStatement(query);
            int filasInsertadas = st.executeUpdate();
            if(filasInsertadas>0)
                System.out.println("operaciones correcta");
            else
                System.out.println("error al insertar hospital");
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jBtn_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VC_Altas_Hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VC_Altas_Hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VC_Altas_Hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VC_Altas_Hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VC_Altas_Hospitales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Registrar;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTF_Calle;
    private javax.swing.JTextField jTF_Ciudad;
    private javax.swing.JTextField jTF_Colonia;
    private javax.swing.JTextField jTF_NSS;
    private javax.swing.JTextField jTF_Nombre;
    private javax.swing.JTextField jTF_NumExt;
    private javax.swing.JTextField jTF_NumInt;
    private javax.swing.JTextField jtf_horario;
    private javax.swing.JTextField jtf_paginaweb;
    private javax.swing.JTextField jtf_tel;
    // End of variables declaration//GEN-END:variables
}
