/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Salva
 */
public class VC_Altas_Pacientes extends javax.swing.JFrame {
    int nssC;
    String primNom,segunNom,apPat,apMat;
    String tel;
    int genero;
    String fechaNac;
    String correo;
    int ocupacion;
    /**
     * Creates new form VC_Altas_Pacientes
     */
    public VC_Altas_Pacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBG_Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_NSS = new javax.swing.JTextField();
        jTF_Nombre1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTF_Nombre2 = new javax.swing.JTextField();
        jTF_ApPaterno = new javax.swing.JTextField();
        jTF_Ap_Materno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_Telefono = new javax.swing.JTextField();
        jRB_Masculino = new javax.swing.JRadioButton();
        jRB_Femenino = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jSpin_Dia = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jCB_Mes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jCB_Año = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTF_Correo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jBtn_Registrar = new javax.swing.JButton();
        jBtn_Salir = new javax.swing.JButton();
        jcb_ocupaciones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(188, 189, 190));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 76, 45), 4));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 76, 45));
        jLabel1.setText("PACIENTE");

        jLabel2.setForeground(new java.awt.Color(29, 76, 45));
        jLabel2.setText("NSS:");

        jTF_NSS.setBackground(new java.awt.Color(255, 255, 255));
        jTF_NSS.setForeground(new java.awt.Color(29, 76, 45));

        jTF_Nombre1.setBackground(new java.awt.Color(255, 255, 255));
        jTF_Nombre1.setForeground(new java.awt.Color(29, 76, 45));

        jLabel3.setForeground(new java.awt.Color(29, 76, 45));
        jLabel3.setText("Nombre:");

        jTF_Nombre2.setBackground(new java.awt.Color(255, 255, 255));
        jTF_Nombre2.setForeground(new java.awt.Color(29, 76, 45));

        jTF_ApPaterno.setBackground(new java.awt.Color(255, 255, 255));
        jTF_ApPaterno.setForeground(new java.awt.Color(29, 76, 45));

        jTF_Ap_Materno.setBackground(new java.awt.Color(255, 255, 255));
        jTF_Ap_Materno.setForeground(new java.awt.Color(29, 76, 45));

        jLabel4.setForeground(new java.awt.Color(29, 76, 45));
        jLabel4.setText("Telefono:");

        jTF_Telefono.setBackground(new java.awt.Color(255, 255, 255));
        jTF_Telefono.setForeground(new java.awt.Color(29, 76, 45));

        jBG_Sexo.add(jRB_Masculino);
        jRB_Masculino.setForeground(new java.awt.Color(29, 76, 45));
        jRB_Masculino.setText("Masculino");

        jBG_Sexo.add(jRB_Femenino);
        jRB_Femenino.setForeground(new java.awt.Color(29, 76, 45));
        jRB_Femenino.setText("Femenino");

        jLabel5.setForeground(new java.awt.Color(29, 76, 45));
        jLabel5.setText("Fecha de nacimiento:");

        jSpin_Dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel6.setForeground(new java.awt.Color(29, 76, 45));
        jLabel6.setText("Día");

        jCB_Mes.setBackground(new java.awt.Color(255, 255, 255));
        jCB_Mes.setForeground(new java.awt.Color(29, 76, 45));
        jCB_Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel7.setForeground(new java.awt.Color(29, 76, 45));
        jLabel7.setText("Mes");

        jCB_Año.setBackground(new java.awt.Color(255, 255, 255));
        jCB_Año.setForeground(new java.awt.Color(29, 76, 45));
        jCB_Año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923" }));

        jLabel8.setForeground(new java.awt.Color(29, 76, 45));
        jLabel8.setText("Año");

        jLabel9.setForeground(new java.awt.Color(29, 76, 45));
        jLabel9.setText("Correo:");

        jTF_Correo.setBackground(new java.awt.Color(255, 255, 255));
        jTF_Correo.setForeground(new java.awt.Color(29, 76, 45));

        jLabel10.setForeground(new java.awt.Color(29, 76, 45));
        jLabel10.setText("Ocupación:");

        jBtn_Registrar.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_Registrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBtn_Registrar.setForeground(new java.awt.Color(29, 76, 45));
        jBtn_Registrar.setText("Registrar");
        jBtn_Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RegistrarActionPerformed(evt);
            }
        });

        jBtn_Salir.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_Salir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBtn_Salir.setForeground(new java.awt.Color(29, 76, 45));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        jcb_ocupaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Trabajador", "Ama/o de casa", "Jubilado/a" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_NSS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTF_Telefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTF_Nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_Nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_ApPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_Ap_Materno, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                            .addComponent(jTF_Correo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpin_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCB_Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCB_Año, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jRB_Masculino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRB_Femenino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jcb_ocupaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jBtn_Registrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_Salir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_NSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_ApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_Ap_Materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTF_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB_Masculino)
                    .addComponent(jRB_Femenino))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpin_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTF_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jcb_ocupaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Registrar)
                    .addComponent(jBtn_Salir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "¿Ha terminado de realizar sus registros?",
                "Confirmación", JOptionPane.YES_NO_OPTION);

        if (x == 0) {
            VC_Main f_Main = new VC_Main();

            f_Main.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_jBtn_SalirActionPerformed

    private void jBtn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RegistrarActionPerformed
        nssC = Integer.parseInt(this.jTF_NSS.getText());
        primNom = "'"+this.jTF_Nombre1.getText()+"'";
        segunNom = "'"+this.jTF_Nombre2.getText()+"'";
        apPat = "'"+this.jTF_ApPaterno.getText()+"'";
        apMat = "'"+this.jTF_Ap_Materno.getText()+"'";
        tel = "'"+this.jTF_Telefono.getText()+"'";
        if(this.jRB_Masculino.isSelected())
            genero = 0;
        else
            genero = 1;
        fechaNac = "'"+this.jSpin_Dia.getValue().toString()+"/"+(this.jCB_Mes.getSelectedIndex()+1)+"/"+this.jCB_Año.getSelectedItem().toString()+"'";
        correo = "'"+this.jTF_Correo.getText()+"'";
        String ocupacionPa = this.jcb_ocupaciones.getSelectedItem().toString();
        switch(ocupacionPa){
            case "Estudiante":
                ocupacion = 1;
                break;
            case "Trabajador":
                ocupacion = 2;
                break;
            case "Ama/o de casa":
                ocupacion = 3;
                break;
            case "Jubilado/a":
                ocupacion = 4;
                break;
        }
        
        String query = "INSERT INTO paciente VALUES("+nssC+","+primNom+","+segunNom+","+apPat+","+apMat+","+tel+","+genero+","+fechaNac+","+correo+","+ocupacion+")"+";";
        try {
            Connection con = ConexionBD.getConexion(ConexionBD.con);
            PreparedStatement st = con.prepareStatement(query);
            int filasInsertadas = st.executeUpdate();
            if(filasInsertadas>0)
                System.out.println("operaciones correcta");
            else
                System.out.println("error al insertar paciente");
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jBtn_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VC_Altas_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VC_Altas_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VC_Altas_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VC_Altas_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VC_Altas_Pacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBG_Sexo;
    private javax.swing.JButton jBtn_Registrar;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JComboBox<String> jCB_Año;
    private javax.swing.JComboBox<String> jCB_Mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRB_Femenino;
    private javax.swing.JRadioButton jRB_Masculino;
    private javax.swing.JSpinner jSpin_Dia;
    private javax.swing.JTextField jTF_ApPaterno;
    private javax.swing.JTextField jTF_Ap_Materno;
    private javax.swing.JTextField jTF_Correo;
    private javax.swing.JTextField jTF_NSS;
    private javax.swing.JTextField jTF_Nombre1;
    private javax.swing.JTextField jTF_Nombre2;
    private javax.swing.JTextField jTF_Telefono;
    private javax.swing.JComboBox<String> jcb_ocupaciones;
    // End of variables declaration//GEN-END:variables

    public String getFecha(){
        String año = this.jCB_Año.getSelectedItem()+"";
        
        String mes = "";
        
        switch(this.jCB_Mes.getSelectedIndex()){
            case 0:
                mes = "01";
                break;
                
            case 1:
                mes = "02";
                break;
                
            case 2:
                mes = "03";
                break;
                
            case 3:
                mes = "04";
                break;
                
            case 4:
                mes = "05";
                break;
                
            case 5:
                mes = "06";
                break;
                
            case 6:
                mes = "07";
                break;
                
            case 7:
                mes = "08";
                break;
                
            case 8:
                mes = "09";
                break;
                
            case 9:
                mes = "10";
                break;
                
            case 10:
                mes = "11";
                break;
                
            case 11:
                mes = "12";
                break;
        }
        
        String dia = this.jSpin_Dia.getValue()+"";
        
        return año + mes + dia;
    }

}
