/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Salva
 */
public class VC_Citas_Agendar extends javax.swing.JFrame {
    String hora;
    String fechaNac;
    String estado;
    String obs;
    int nss,numMed,idHosp;
    /**
     * Creates new form VC_Altas_Pacientes
     */
    public VC_Citas_Agendar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTF_Estado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpin_Dia = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jCB_Mes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jCB_Año = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jBtn_Agendar = new javax.swing.JButton();
        jBtn_Salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_Observaciones = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpin_Hora = new javax.swing.JSpinner();
        jSpin_Minuto = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jcb_nss = new javax.swing.JComboBox<>();
        jcb_numMed = new javax.swing.JComboBox<>();
        jcb_idHosp = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(188, 189, 190));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 76, 45), 4));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 76, 45));
        jLabel1.setText("CITAS");

        jLabel3.setForeground(new java.awt.Color(29, 76, 45));
        jLabel3.setText("Hora:");

        jLabel4.setForeground(new java.awt.Color(29, 76, 45));
        jLabel4.setText("Estado:");

        jTF_Estado.setBackground(new java.awt.Color(255, 255, 255));
        jTF_Estado.setForeground(new java.awt.Color(29, 76, 45));

        jLabel5.setForeground(new java.awt.Color(29, 76, 45));
        jLabel5.setText("Fecha:");

        jSpin_Dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel6.setForeground(new java.awt.Color(29, 76, 45));
        jLabel6.setText("Día");

        jCB_Mes.setBackground(new java.awt.Color(255, 255, 255));
        jCB_Mes.setForeground(new java.awt.Color(29, 76, 45));
        jCB_Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel7.setForeground(new java.awt.Color(29, 76, 45));
        jLabel7.setText("Mes");

        jCB_Año.setBackground(new java.awt.Color(255, 255, 255));
        jCB_Año.setForeground(new java.awt.Color(29, 76, 45));
        jCB_Año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923" }));

        jLabel8.setForeground(new java.awt.Color(29, 76, 45));
        jLabel8.setText("Año");

        jLabel9.setForeground(new java.awt.Color(29, 76, 45));
        jLabel9.setText("Observaciones:");

        jLabel10.setForeground(new java.awt.Color(29, 76, 45));
        jLabel10.setText("NSS del paciente:");

        jBtn_Agendar.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_Agendar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBtn_Agendar.setForeground(new java.awt.Color(29, 76, 45));
        jBtn_Agendar.setText("Agendar");
        jBtn_Agendar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtn_Agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AgendarActionPerformed(evt);
            }
        });

        jBtn_Salir.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_Salir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBtn_Salir.setForeground(new java.awt.Color(29, 76, 45));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        jTA_Observaciones.setBackground(new java.awt.Color(255, 255, 255));
        jTA_Observaciones.setColumns(20);
        jTA_Observaciones.setForeground(new java.awt.Color(29, 76, 45));
        jTA_Observaciones.setRows(5);
        jScrollPane1.setViewportView(jTA_Observaciones);

        jLabel11.setForeground(new java.awt.Color(29, 76, 45));
        jLabel11.setText("Numero de reg. del médico:");

        jLabel12.setForeground(new java.awt.Color(29, 76, 45));
        jLabel12.setText("Hospital:");

        jSpin_Hora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        jSpin_Minuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel13.setForeground(new java.awt.Color(29, 76, 45));
        jLabel13.setText(":");

        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Estado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSpin_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jSpin_Minuto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpin_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCB_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCB_Año, 0, 64, Short.MAX_VALUE)))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_nss, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcb_numMed, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jButton1))
                            .addComponent(jcb_idHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jBtn_Agendar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jBtn_Salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(73, 73, 73)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(198, 198, 198))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpin_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpin_Minuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpin_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTF_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jcb_nss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcb_numMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jcb_idHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Agendar)
                    .addComponent(jBtn_Salir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "¿Ha terminado de agendar las citas?",
                "Confirmación", JOptionPane.YES_NO_OPTION);

        if (x == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jBtn_SalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection conec = null;
        try {
            conec = ConexionBD.getConexion(conec);
            String sentenciaSQL = "SELECT pac_nssPac from paciente";
            String sentenciaSQL2 = "SELECT med_numRegistroMedico from medico";
            String sentenciaSQL3 = "SELECT hosp_idHosp from hospital";
            Statement statement = conec.createStatement();
            ResultSet resultSet = statement.executeQuery(sentenciaSQL);
            while (resultSet.next()) {
                String clavePrimaria = resultSet.getString("pac_nssPac");
                this.jcb_nss.addItem(clavePrimaria);
            }
            
            statement = conec.createStatement();
            resultSet = statement.executeQuery(sentenciaSQL2);
            while (resultSet.next()) {
                String clavePrimaria = resultSet.getString("med_numRegistroMedico");
                this.jcb_numMed.addItem(clavePrimaria);
            }
            
            statement = conec.createStatement();
            resultSet = statement.executeQuery(sentenciaSQL3);
            while (resultSet.next()) {
                String clavePrimaria = resultSet.getString("hosp_idHosp");
                this.jcb_idHosp.addItem(clavePrimaria);
            }

            // Cierra los recursos JDBC
            resultSet.close();
            statement.close();
            conec.close();
        } catch (SQLException ex) {
            Logger.getLogger(VC_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtn_AgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AgendarActionPerformed
       hora = "'"+this.jSpin_Hora.getValue().toString()+":"+this.jSpin_Minuto.getValue().toString()+":00"+"'";
       JOptionPane.showMessageDialog(null, hora);
       fechaNac = "'"+this.jSpin_Dia.getValue().toString()+"/"+(this.jCB_Mes.getSelectedIndex()+1)+"/"+this.jCB_Año.getSelectedItem().toString()+"'";
       estado = "'"+this.jTF_Estado.getText()+"'";
       obs = "'"+this.jTA_Observaciones.getText()+"'";
       nss = Integer.parseInt(this.jcb_nss.getSelectedItem().toString());
       numMed = Integer.parseInt(this.jcb_numMed.getSelectedItem().toString());
       idHosp = Integer.parseInt(this.jcb_idHosp.getSelectedItem().toString());
        String query = "INSERT INTO cita VALUES("+hora+","+fechaNac+","+estado+","+obs+","+nss+","+numMed+","+idHosp+");";
        
       try {
            Connection con = ConexionBD.getConexion(ConexionBD.con);
            PreparedStatement st = con.prepareStatement(query);
            int filasInsertadas = st.executeUpdate();
            if(filasInsertadas>0)
                System.out.println("operaciones correcta");
            else
                System.out.println("error al insertar cita");
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jBtn_AgendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VC_Citas_Agendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VC_Citas_Agendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VC_Citas_Agendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VC_Citas_Agendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VC_Citas_Agendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Agendar;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCB_Año;
    private javax.swing.JComboBox<String> jCB_Mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpin_Dia;
    private javax.swing.JSpinner jSpin_Hora;
    private javax.swing.JSpinner jSpin_Minuto;
    private javax.swing.JTextArea jTA_Observaciones;
    private javax.swing.JTextField jTF_Estado;
    private javax.swing.JComboBox<String> jcb_idHosp;
    private javax.swing.JComboBox<String> jcb_nss;
    private javax.swing.JComboBox<String> jcb_numMed;
    // End of variables declaration//GEN-END:variables

    public String getFecha(){
        String año = this.jCB_Año.getSelectedItem()+"";
        
        String mes = "";
        
        switch(this.jCB_Mes.getSelectedIndex()){
            case 0:
                mes = "01";
                break;
                
            case 1:
                mes = "02";
                break;
                
            case 2:
                mes = "03";
                break;
                
            case 3:
                mes = "04";
                break;
                
            case 4:
                mes = "05";
                break;
                
            case 5:
                mes = "06";
                break;
                
            case 6:
                mes = "07";
                break;
                
            case 7:
                mes = "08";
                break;
                
            case 8:
                mes = "09";
                break;
                
            case 9:
                mes = "10";
                break;
                
            case 10:
                mes = "11";
                break;
                
            case 11:
                mes = "12";
                break;
        }
        
        String dia = this.jSpin_Dia.getValue()+"";
        
        return año + mes + dia;
    }

}
