/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Salva
 */
public class VC_Main extends javax.swing.JFrame {

    /**
     * Creates new form VC_Main
     */
    public VC_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jBtn_Salir = new javax.swing.JButton();
        jBtn_Altas = new javax.swing.JButton();
        jBtn_Citas = new javax.swing.JButton();
        jBtn_Ver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLab_Info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VitaCare Software (c)");
        setBackground(new java.awt.Color(188, 189, 190));

        Background.setBackground(new java.awt.Color(188, 189, 190));

        jBtn_Salir.setBackground(new java.awt.Color(29, 76, 45));
        jBtn_Salir.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jBtn_Salir.setForeground(new java.awt.Color(188, 189, 190));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        jBtn_Altas.setBackground(new java.awt.Color(29, 76, 45));
        jBtn_Altas.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jBtn_Altas.setForeground(new java.awt.Color(188, 189, 190));
        jBtn_Altas.setText("Altas");
        jBtn_Altas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtn_Altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AltasActionPerformed(evt);
            }
        });

        jBtn_Citas.setBackground(new java.awt.Color(29, 76, 45));
        jBtn_Citas.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jBtn_Citas.setForeground(new java.awt.Color(188, 189, 190));
        jBtn_Citas.setText("Citas");
        jBtn_Citas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtn_Citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CitasActionPerformed(evt);
            }
        });

        jBtn_Ver.setBackground(new java.awt.Color(29, 76, 45));
        jBtn_Ver.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jBtn_Ver.setForeground(new java.awt.Color(188, 189, 190));
        jBtn_Ver.setText("Ver");
        jBtn_Ver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtn_Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_VerActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/VC_Medical.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLab_Info.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_Info.setForeground(new java.awt.Color(29, 76, 45));
        jLab_Info.setText("info");
        jLab_Info.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLab_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLab_InfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLab_InfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLab_InfoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(jBtn_Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLab_Info)
                        .addGap(152, 152, 152)
                        .addComponent(jBtn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jBtn_Altas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_Citas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Altas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_Citas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLab_Info))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_VerActionPerformed
        try {
            VC_Main_Ver f_Ver = new VC_Main_Ver();
            
            f_Ver.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(VC_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtn_VerActionPerformed

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jBtn_SalirActionPerformed

    private void jBtn_AltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AltasActionPerformed
        
        VC_Altas f_Altas = new VC_Altas();
        
        f_Altas.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jBtn_AltasActionPerformed

    private void jBtn_CitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CitasActionPerformed
        
        
        
        VC_Citas f_Citas = new VC_Citas();
        
        f_Citas.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jBtn_CitasActionPerformed

    private void jLab_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab_InfoMouseClicked
        JOptionPane.showMessageDialog(null, "Created by:\n"+
                "Victor Manuel Tijerina Garnica \n"+
                "Pablo Ivan Amaya Aldaba \n" +
                "Salvador Frausto Carrillo",
                "INFO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLab_InfoMouseClicked

    private void jLab_InfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab_InfoMouseEntered
        this.jLab_Info.setForeground(new Color(53, 144, 84));
    }//GEN-LAST:event_jLab_InfoMouseEntered

    private void jLab_InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab_InfoMouseExited
        this.jLab_Info.setForeground(new Color(29, 76, 45));
    }//GEN-LAST:event_jLab_InfoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VC_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VC_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VC_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VC_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VC_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton jBtn_Altas;
    private javax.swing.JButton jBtn_Citas;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JButton jBtn_Ver;
    private javax.swing.JLabel jLab_Info;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
